
package com.elektra.uniformes.comercio.DAO.LlaveMaestaWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Valida_sesion", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.50.158.63/login5/valida_sesion/valida_sesion.asmx?WSDL")
public class ValidaSesion
    extends Service
{

    private final static URL VALIDASESION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.DAO.LlaveMaestaWS.ValidaSesion.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.DAO.LlaveMaestaWS.ValidaSesion.class.getResource(".");
            url = new URL(baseUrl, "http://10.50.158.63/login5/valida_sesion/valida_sesion.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.50.158.63/login5/valida_sesion/valida_sesion.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VALIDASESION_WSDL_LOCATION = url;
    }

    public ValidaSesion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaSesion() {
        super(VALIDASESION_WSDL_LOCATION, new QName("http://tempuri.org/", "Valida_sesion"));
    }

    /**
     * 
     * @return
     *     returns ValidaSesionSoap
     */
    @WebEndpoint(name = "Valida_sesionSoap")
    public ValidaSesionSoap getValidaSesionSoap() {
        return super.getPort(new QName("http://tempuri.org/", "Valida_sesionSoap"), ValidaSesionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaSesionSoap
     */
    @WebEndpoint(name = "Valida_sesionSoap")
    public ValidaSesionSoap getValidaSesionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Valida_sesionSoap"), ValidaSesionSoap.class, features);
    }

}
