
package com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWSUniformes", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWSUniformes {


    /**
     * 
     * @param recive
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.CreaPedido
     */
    @WebMethod(operationName = "GeneraPedido", action = "http://tempuri.org/IWSUniformes/GeneraPedido")
    @WebResult(name = "GeneraPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraPedido", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.GeneraPedido")
    @ResponseWrapper(localName = "GeneraPedidoResponse", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.GeneraPedidoResponse")
    public CreaPedido generaPedido(
        @WebParam(name = "Recive", targetNamespace = "http://tempuri.org/")
        ReciveDatos recive);

    /**
     * 
     * @param datosP
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.SalidaDatos
     */
    @WebMethod(operationName = "ActualizaPedido", action = "http://tempuri.org/IWSUniformes/ActualizaPedido")
    @WebResult(name = "ActualizaPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActualizaPedido", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ActualizaPedido")
    @ResponseWrapper(localName = "ActualizaPedidoResponse", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ActualizaPedidoResponse")
    public SalidaDatos actualizaPedido(
        @WebParam(name = "DatosP", targetNamespace = "http://tempuri.org/")
        AtualizaPedidos datosP);

    /**
     * 
     * @param datosP
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ConsultaPedidos
     */
    @WebMethod(operationName = "ConsultaPedido", action = "http://tempuri.org/IWSUniformes/ConsultaPedido")
    @WebResult(name = "ConsultaPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaPedido", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ConsultaPedido")
    @ResponseWrapper(localName = "ConsultaPedidoResponse", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ConsultaPedidoResponse")
    public ConsultaPedidos consultaPedido(
        @WebParam(name = "DatosP", targetNamespace = "http://tempuri.org/")
        ConsultaPedidosEntrada datosP);

    /**
     * 
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ArrayOfKeyValueOfstringstring
     */
    @WebMethod(operationName = "ConsultaParametros", action = "http://tempuri.org/IWSUniformes/ConsultaParametros")
    @WebResult(name = "ConsultaParametrosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaParametros", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ConsultaParametros")
    @ResponseWrapper(localName = "ConsultaParametrosResponse", targetNamespace = "http://tempuri.org/", className = "com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.ConsultaParametrosResponse")
    public ArrayOfKeyValueOfstringstring consultaParametros();

}
