
package com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSUniformes", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.54.28.114/WebServicioTienda/Elektra.Servicios.Datos.AdmonUniformes.WSUniformes.svc?wsdl")
public class WSUniformes
    extends Service
{

    private final static URL WSUNIFORMES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.WSUniformes.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.cron.dao.clienteWS.tienda.WSUniformes.class.getResource(".");
            url = new URL(baseUrl, "http://10.54.28.114/WebServicioTienda/Elektra.Servicios.Datos.AdmonUniformes.WSUniformes.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.54.28.114/WebServicioTienda/Elektra.Servicios.Datos.AdmonUniformes.WSUniformes.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSUNIFORMES_WSDL_LOCATION = url;
    }

    public WSUniformes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUniformes() {
        super(WSUNIFORMES_WSDL_LOCATION, new QName("http://tempuri.org/", "WSUniformes"));
    }

    /**
     * 
     * @return
     *     returns IWSUniformes
     */
    @WebEndpoint(name = "BasicHttpBinding_IWSUniformes")
    public IWSUniformes getBasicHttpBindingIWSUniformes() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWSUniformes"), IWSUniformes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSUniformes
     */
    @WebEndpoint(name = "BasicHttpBinding_IWSUniformes")
    public IWSUniformes getBasicHttpBindingIWSUniformes(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWSUniformes"), IWSUniformes.class, features);
    }

}
