CREATE BIGFILE TABLESPACE TBS_UNIFORMES_CAT_DAT DATAFILE 
  '+DGPVBDDES02/tbs_uniformes_cat_dat.dbf' SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE BIGFILE TABLESPACE TBS_UNIFORMES_CAT_IDX DATAFILE 
  '+DGPVBDDES02/tbs_uniformes_cat_idx.dbf' SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE BIGFILE TABLESPACE TBS_UNIFORMES_OPE_DAT DATAFILE 
  '+DGPVBDDES02/tbs_uniformes_ope_dat.dbf' SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE BIGFILE TABLESPACE TBS_UNIFORMES_OPE_IDX DATAFILE 
  '+DGPVBDDES02/tbs_uniformes_ope_idx.dbf' SIZE 250M AUTOEXTEND ON NEXT 50M MAXSIZE 34359738344K
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE USER UNIFORMES
  IDENTIFIED BY UNIFORMES
  DEFAULT TABLESPACE TBS_UNIFORMES_CAT_DAT
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 3 Roles for UNIFORMES 
  GRANT RESOURCE TO UNIFORMES;
  GRANT SCHEDULER_ADMIN TO UNIFORMES;
  GRANT CONNECT TO UNIFORMES;
  ALTER USER UNIFORMES DEFAULT ROLE ALL;
  -- 3 System Privileges for UNIFORMES 
  GRANT UNLIMITED TABLESPACE TO UNIFORMES;
  GRANT CREATE SESSION TO UNIFORMES;
  GRANT ON COMMIT REFRESH TO UNIFORMES;
  -- 4 Tablespace Quotas for UNIFORMES 
  ALTER USER UNIFORMES QUOTA UNLIMITED ON TBS_UNIFORMES_OPE_IDX;
  ALTER USER UNIFORMES QUOTA UNLIMITED ON TBS_UNIFORMES_CAT_DAT;
  ALTER USER UNIFORMES QUOTA UNLIMITED ON TBS_UNIFORMES_OPE_DAT;
  ALTER USER UNIFORMES QUOTA UNLIMITED ON TBS_UNIFORMES_CAT_IDX;
  
  