
package com.elektra.uniformes.comercio.DAO.clienteWS.InventarioCD;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "intfCONSUL_INVENTARIO-service", targetNamespace = "http://servicios.elektra.com.mx/ekt/1.0/inventario", wsdlLocation = "file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod_1/WS_INVENTARIO.wsdl")
public class IntfCONSULINVENTARIOService
    extends Service
{

    private final static URL INTFCONSULINVENTARIOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.DAO.clienteWS.InventarioCD.IntfCONSULINVENTARIOService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.DAO.clienteWS.InventarioCD.IntfCONSULINVENTARIOService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod_1/WS_INVENTARIO.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod_1/WS_INVENTARIO.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTFCONSULINVENTARIOSERVICE_WSDL_LOCATION = url;
    }

    public IntfCONSULINVENTARIOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntfCONSULINVENTARIOService() {
        super(INTFCONSULINVENTARIOSERVICE_WSDL_LOCATION, new QName("http://servicios.elektra.com.mx/ekt/1.0/inventario", "intfCONSUL_INVENTARIO-service"));
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsCONSUL_INVENTARIOEndpoint1")
    public PortType getIntfwsCONSULINVENTARIOEndpoint1() {
        return super.getPort(new QName("http://servicios.elektra.com.mx/ekt/1.0/inventario", "intfwsCONSUL_INVENTARIOEndpoint1"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsCONSUL_INVENTARIOEndpoint1")
    public PortType getIntfwsCONSULINVENTARIOEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.elektra.com.mx/ekt/1.0/inventario", "intfwsCONSUL_INVENTARIOEndpoint1"), PortType.class, features);
    }

}
