
package com.elektra.uniformes.comercio.DAO.clienteWS.InventarioCD;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "portType", targetNamespace = "http://servicios.elektra.com.mx/ekt/1.0/inventario")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.elektra.uniformes.comercio.DAO.clienteWS.InventarioCD.Parametros
     */
    @WebMethod(operationName = "CONSUL__INVENTARIOOp", action = "/BusinessProcesses/Systems/WSEvents/intfCONSUL_INVENTARIO-service.serviceagent/intfwsCONSUL_INVENTARIOEndpoint1/CONSUL__INVENTARIOOp")
    @WebResult(name = "Parametros", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Salid_Inventario", partName = "parameters")
    public Parametros consulINVENTARIOOp(
        @WebParam(name = "Parametros_Entrada", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Entr_Inventario", partName = "parameters")
        ParametrosEntrada parameters);

}
