/*************************************************************
Proyecto: Uniformes Comercio v2
Descripcion: Crea el usuario, las tablas e indices.
Valor de retorno: Resultado de ejecucion de cada linea.
Precondiciones: Ninguna   
Creador: Luis Daniel Rodriguez Garcia
Fecha de creacion: 27 Diciembre 2017
*************************************************************/

--Modelo de BD--------------------------------------------------------------------
-- CREACION USUARIO SISTEMA WEB
CREATE USER USRUNIFORMESCOMERCIOWEB
   IDENTIFIED BY PSWUNIFORMESCOMERCIOWEB
   DEFAULT TABLESPACE USERS
   TEMPORARY TABLESPACE TEMP 
   PROFILE DEFAULT
   ACCOUNT UNLOCK;
   GRANT CREATE SESSION TO USRUNIFORMESCOMERCIOWEB;

-- USUARIO CRON
CREATE USER USRUNIFORMESCOMERCIOSRV
   IDENTIFIED BY PSWUNIFORMESCOMERCIOSRV
   DEFAULT TABLESPACE USERS
   TEMPORARY TABLESPACE TEMP 
   PROFILE DEFAULT
   ACCOUNT UNLOCK;
   GRANT CREATE SESSION TO USRUNIFORMESCOMERCIOSRV;
   
--24) TABLA OPERATIVA CARGAMENTOS
CREATE TABLE UNIFORMES.TACARGASSEMESTRALES (
    FIIDCARGA       NUMBER(5) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(40 CHAR) NOT NULL,
    FDFECHAINICIAL  DATE NOT NULL,
    FDFECHAFINAL    DATE NOT NULL,
    FIGENERARPEDIDO NUMBER(1) NOT NULL,
    FIESTATUS       NUMBER(3) DEFAULT 0 NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACARGASSEMESTRALES ON UNIFORMES.TACARGASSEMESTRALES(FIIDCARGA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX; 

-- CREACION PK
ALTER TABLE UNIFORMES.TACARGASSEMESTRALES 
    ADD CONSTRAINT PK_TACARGASSEMESTRALES 
    PRIMARY KEY ( FIIDCARGA ) 
    USING INDEX UNIFORMES.PK_TACARGASSEMESTRALES;

--14) TABLA CATALOGO ESTATUS PEDIDOS
CREATE TABLE UNIFORMES.TAESTATUSPEDIDOS (
    FIIDESTATUSPEDIDO   NUMBER(3) NOT NULL, --PK
    FCDESCRIPCION       VARCHAR2(50 CHAR) NOT NULL
)    
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAESTATUSPEDIDOS ON UNIFORMES.TAESTATUSPEDIDOS(FIIDESTATUSPEDIDO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAESTATUSPEDIDOS 
    ADD CONSTRAINT PK_TAESTATUSPEDIDOS 
    PRIMARY KEY ( FIIDESTATUSPEDIDO ) 
    USING INDEX UNIFORMES.PK_TAESTATUSPEDIDOS;

--3) TABLA CATALOGO TIPO KIT
CREATE TABLE UNIFORMES.TATIPOKIT(
    FIKIT           NUMBER(5) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(60 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOKIT ON UNIFORMES.TATIPOKIT(FIKIT)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOKIT 
    ADD CONSTRAINT PK_TATIPOKIT 
    PRIMARY KEY ( FIKIT ) 
    USING INDEX UNIFORMES.PK_TATIPOKIT;

--11) TABLA CATALOGO TIPO TALLA
CREATE TABLE UNIFORMES.TATIPOTALLA(
    FITALLA         NUMBER(5) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(60 CHAR) NOT NULL,
    FCCLAVE         VARCHAR2(20 CHAR) NOT NULL,
    FIORDEN         NUMBER(10) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOTALLA ON UNIFORMES.TATIPOTALLA(FITALLA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOTALLA 
    ADD CONSTRAINT PK_TATIPOTALLA 
    PRIMARY KEY ( FITALLA ) 
    USING INDEX UNIFORMES.PK_TATIPOTALLA;

--12) TABLA CATALOGO TIPOS PRENDA
CREATE TABLE UNIFORMES.TATIPOSPRENDA (
    FIIDTIPOPRENDA  NUMBER(3) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(50 CHAR) NOT NULL,
    FCIMAGEN        VARCHAR2(300 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOSPRENDA ON UNIFORMES.TATIPOSPRENDA(FIIDTIPOPRENDA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX; 

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOSPRENDA 
    ADD CONSTRAINT PK_TATIPOSPRENDA 
    PRIMARY KEY ( FIIDTIPOPRENDA ) 
    USING INDEX UNIFORMES.PK_TATIPOSPRENDA;

--5) TABLA CATALOGO GENERO
CREATE TABLE UNIFORMES.TAGENERO (
    FIIDGENERO      NUMBER(3) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(50 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAGENERO ON UNIFORMES.TAGENERO(FIIDGENERO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;    

-- CREACION PK
ALTER TABLE UNIFORMES.TAGENERO 
    ADD CONSTRAINT PK_TAGENERO 
    PRIMARY KEY ( FIIDGENERO ) 
    USING INDEX UNIFORMES.PK_TAGENERO;

--6) TABLA CATALOGO TALLAS X TIPO PRENDA
CREATE TABLE UNIFORMES.TATALLASXTIPOPRENDA (
    FIIDTIPOPRENDA  NUMBER(3) NOT NULL, --PK
    FITALLA         NUMBER(3) NOT NULL, --PK
    FIIDGENERO      NUMBER(3) NOT NULL  --PK
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATALLASXTIPOPRENDA ON UNIFORMES.TATALLASXTIPOPRENDA(FIIDTIPOPRENDA, FITALLA , FIIDGENERO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATALLASXTIPOPRENDA 
    ADD CONSTRAINT PK_TATALLASXTIPOPRENDA 
    PRIMARY KEY ( FIIDTIPOPRENDA,FITALLA,FIIDGENERO ) 
    USING INDEX UNIFORMES.PK_TATALLASXTIPOPRENDA;

-- CREACION FK
ALTER TABLE UNIFORMES.TATALLASXTIPOPRENDA 
    ADD CONSTRAINT FK_TATALLASXTIPOPRENDA_01 
    FOREIGN KEY ( FIIDGENERO ) 
    REFERENCES UNIFORMES.TAGENERO ( FIIDGENERO );

-- CREACION FK
ALTER TABLE UNIFORMES.TATALLASXTIPOPRENDA 
    ADD CONSTRAINT FK_TATALLASXTIPOPRENDA_02 
    FOREIGN KEY ( FIIDTIPOPRENDA ) 
    REFERENCES UNIFORMES.TATIPOSPRENDA ( FIIDTIPOPRENDA );

-- CREACION FK
ALTER TABLE UNIFORMES.TATALLASXTIPOPRENDA
    ADD CONSTRAINT FK_TATALLASXTIPOPRENDA_03 
    FOREIGN KEY ( FITALLA )
    REFERENCES UNIFORMES.TATIPOTALLA ( FITALLA );

--1) TABLA CATALOGO PRENDAS
CREATE TABLE UNIFORMES.TAPRENDAS (
    FISKU           NUMBER(20) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(50 CHAR) NOT NULL,
    FIIDTIPOPRENDA  NUMBER(3) NOT NULL,
    FITALLA         NUMBER(3) NOT NULL,
    FIIDGENERO      NUMBER(3) NOT NULL,
    FNCOSTO         NUMBER(10,2) NOT NULL,
    FIDISCONTINUO   NUMBER(3) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAPRENDAS ON UNIFORMES.TAPRENDAS(FISKU)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAPRENDAS 
    ADD CONSTRAINT PK_TAPRENDAS
    PRIMARY KEY ( FISKU )
    USING INDEX UNIFORMES.PK_TAPRENDAS;

-- CREACION FK
ALTER TABLE UNIFORMES.TAPRENDAS
    ADD CONSTRAINT FK_TAPRENDAS_01 
    FOREIGN KEY ( FIIDTIPOPRENDA,FITALLA,FIIDGENERO )
    REFERENCES UNIFORMES.TATALLASXTIPOPRENDA ( FIIDTIPOPRENDA,FITALLA,FIIDGENERO );

--2) TABLA CATALOGO SKUS X KIT
CREATE TABLE UNIFORMES.TASKUSXKIT (
    FISKU   NUMBER(20) NOT NULL,    --PK
    FIKIT   NUMBER(10) NOT NULL     --PK
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TASKUSXKIT ON UNIFORMES.TASKUSXKIT(FISKU, FIKIT)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TASKUSXKIT 
    ADD CONSTRAINT PK_TASKUSXKIT 
    PRIMARY KEY ( FISKU,FIKIT ) 
    USING INDEX UNIFORMES.PK_TASKUSXKIT;

-- CREACION FK
ALTER TABLE UNIFORMES.TASKUSXKIT
    ADD CONSTRAINT FK_TASKUSXKIT_01 FOREIGN KEY ( FIKIT )
    REFERENCES UNIFORMES.TATIPOKIT ( FIKIT );

-- CREACION FK
ALTER TABLE UNIFORMES.TASKUSXKIT
    ADD CONSTRAINT FK_TASKUSXKIT_02 FOREIGN KEY ( FISKU )
    REFERENCES UNIFORMES.TAPRENDAS ( FISKU );
	
--23) TABLA CATALOGO NEGOCIOS
CREATE TABLE UNIFORMES.TANEGOCIOS (
    FIIDNEGOCIO         NUMBER(3) NOT NULL, --PK
    FCDESCRIPCION       VARCHAR2(50 CHAR) NOT NULL,
    FCDESCRCORTA        VARCHAR2(30 CHAR) NOT NULL,
    FISOLICITAENTIENDA  NUMBER(1) DEFAULT 1
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TANEGOCIOS ON UNIFORMES.TANEGOCIOS(FIIDNEGOCIO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TANEGOCIOS 
    ADD CONSTRAINT PK_TANEGOCIOS 
    PRIMARY KEY ( FIIDNEGOCIO ) 
    USING INDEX UNIFORMES.PK_TANEGOCIOS;

--4) TABLA CATALOGO FUNCIONES X NEGOCIO
CREATE TABLE UNIFORMES.TAFUNCIONESXNEGOCIO (
    FIIDNEGOCIO             NUMBER(3) NOT NULL,     --PK
    FIFUNCIONSAP            NUMBER(10) NOT NULL,    --PK
    FIKIT                   NUMBER(10) NOT NULL,
    FCDESCFUNCION           VARCHAR2(300 CHAR) DEFAULT ' ' NOT NULL,
    FISOLICITUDPLANTILLA    NUMBER(1) DEFAULT 0,
    FICANAL                 NUMBER(10) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAFUNCIONESXNEGOCIO ON UNIFORMES.TAFUNCIONESXNEGOCIO(FIIDNEGOCIO, FIFUNCIONSAP)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAFUNCIONESXNEGOCIO 
    ADD CONSTRAINT PK_TAFUNCIONESXNEGOCIO 
    PRIMARY KEY ( FIIDNEGOCIO,FIFUNCIONSAP ) 
    USING INDEX UNIFORMES.PK_TAFUNCIONESXNEGOCIO;

-- CREACION FK
ALTER TABLE UNIFORMES.TAFUNCIONESXNEGOCIO
    ADD CONSTRAINT FK_TAFUNCIONESXNEGOCIO_01 
    FOREIGN KEY ( FIKIT )
    REFERENCES UNIFORMES.TATIPOKIT ( FIKIT );

-- CREACION FK
ALTER TABLE UNIFORMES.TAFUNCIONESXNEGOCIO
    ADD CONSTRAINT FK_TAFUNCIONESXNEGOCIO_02 
    FOREIGN KEY ( FIIDNEGOCIO )
    REFERENCES UNIFORMES.TANEGOCIOS ( FIIDNEGOCIO );

--7) TABLA CATALOGO TIPOS PRENDA X KIT
CREATE TABLE UNIFORMES.TATIPOSPRENDAXKIT (
    FIKIT           NUMBER(10) NOT NULL,    --PK
    FIIDTIPOPRENDA  NUMBER(3) NOT NULL      --PK
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOSPRENDAXKIT ON UNIFORMES.TATIPOSPRENDAXKIT(FIKIT, FIIDTIPOPRENDA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;   

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOSPRENDAXKIT 
    ADD CONSTRAINT PK_TATIPOSPRENDAXKIT 
    PRIMARY KEY ( FIKIT,FIIDTIPOPRENDA ) 
    USING INDEX UNIFORMES.PK_TATIPOSPRENDAXKIT;

-- CREACION FK
ALTER TABLE UNIFORMES.TATIPOSPRENDAXKIT
    ADD CONSTRAINT FK_TATIPOSPRENDAXKIT_01 FOREIGN KEY ( FIKIT )
    REFERENCES UNIFORMES.TATIPOKIT ( FIKIT );

-- CREACION FK
ALTER TABLE UNIFORMES.TATIPOSPRENDAXKIT
    ADD CONSTRAINT FK_TATIPOSPRENDAXKIT_02 FOREIGN KEY ( FIIDTIPOPRENDA )
    REFERENCES UNIFORMES.TATIPOSPRENDA ( FIIDTIPOPRENDA );

--21) TABLA CATALOGO TIPO SOLICITUD
CREATE TABLE UNIFORMES.TATIPOSOLICITUD (
    FIIDTIPOSOLICITUD   NUMBER(3) NOT NULL, --PK
    FCDESCRIPCION       VARCHAR2(50 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOSOLICITUD ON UNIFORMES.TATIPOSOLICITUD(FIIDTIPOSOLICITUD)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOSOLICITUD 
    ADD CONSTRAINT PK_TATIPOSOLICITUD 
    PRIMARY KEY ( FIIDTIPOSOLICITUD ) 
    USING INDEX UNIFORMES.PK_TATIPOSOLICITUD;

--22) TABLA OPERATIVA SOLICITUDES
CREATE TABLE UNIFORMES.TASOLICITUDES (
    FIFOLIOSOLICITUD    NUMBER(20) NOT NULL, --PK
    FIIDEMPLEADO        NUMBER(10) NOT NULL,
    FIIDTIPOSOLICITUD   NUMBER(3) NOT NULL,
    FIIDNEGOCIO         NUMBER(3) NOT NULL,
    FIFUNCIONSAP        NUMBER(10) NOT NULL,
    FIIDEMPCAPTURA      NUMBER(10) NOT NULL,
    FDFECHACAPTURA      DATE NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TASOLICITUDES ON UNIFORMES.TASOLICITUDES(FIFOLIOSOLICITUD)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TASOLICITUDES 
    ADD CONSTRAINT PK_TASOLICITUDES 
    PRIMARY KEY ( FIFOLIOSOLICITUD ) 
    USING INDEX UNIFORMES.PK_TASOLICITUDES;

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDES
    ADD CONSTRAINT FK_TASOLICITUDES_01
    FOREIGN KEY ( FIIDNEGOCIO )
    REFERENCES UNIFORMES.TANEGOCIOS ( FIIDNEGOCIO );

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDES
    ADD CONSTRAINT FK_TASOLICITUDES_02 
    FOREIGN KEY ( FIIDTIPOSOLICITUD )
    REFERENCES UNIFORMES.TATIPOSOLICITUD ( FIIDTIPOSOLICITUD );

--10) TABLA CATALOGO TIENDAS
CREATE TABLE UNIFORMES.TATIENDAS (
    FIPAIS                  NUMBER(3) NOT NULL,     --PK
    FICANAL                 NUMBER(10) NOT NULL,    --PK   
    FISUCURSAL              NUMBER(10) NOT NULL,    --PK
    FCNOMBRE                VARCHAR2(100 CHAR) NOT NULL,
    FCDIRIP                 VARCHAR2(20 CHAR) NOT NULL,
    FIIDCDISTRIBUCION       NUMBER(10) NOT NULL,
    FIIDFORMADOR            NUMBER(10) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIENDAS ON UNIFORMES.TATIENDAS(FIPAIS,FICANAL, FISUCURSAL)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIENDAS
    ADD CONSTRAINT PK_TATIENDAS 
    PRIMARY KEY ( FIPAIS,FICANAL,FISUCURSAL) 
    USING INDEX UNIFORMES.PK_TATIENDAS;

CREATE TABLE UNIFORMES.TAESTATUSABASTO(
    FIESTATUS       NUMBER (20) NOT NULL,
    FCMENSAJE       VARCHAR2 (100 CHAR)
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;
    
CREATE UNIQUE INDEX UNIFORMES.PK_TAESTATUSABASTO ON UNIFORMES.TAESTATUSABASTO(FIESTATUS)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

ALTER TABLE UNIFORMES.TAESTATUSABASTO
    ADD CONSTRAINT PK_TAESTATUSABASTO
    PRIMARY KEY (FIESTATUS)
    USING INDEX UNIFORMES.PK_TAESTATUSABASTO;
    
--16) TABLA OPERATIVA SOLICITUDES DETALLE
CREATE TABLE UNIFORMES.TASOLICITUDESDETALLE (
    FIFOLIOSOLICITUD    NUMBER (20) NOT NULL, --PK
    FIIDDETALLE         NUMBER (10) NOT NULL, --PK
    FIPAIS              NUMBER (3) NOT NULL,  --PK
    FICANAL             NUMBER (10) NOT NULL, --PK	
    FISUCURSAL          NUMBER (10) NOT NULL, --PK	
    FIPEDIDO            NUMBER (10) NOT NULL, --PK
    FISKU               NUMBER (12) NOT NULL, --PK
    FIIDTIPOPRENDA      NUMBER (3) NOT NULL, 
    FITALLA             NUMBER (10) NOT NULL,
    FICANTIDAD          NUMBER (3) NOT NULL,
    FNPRECIOUNITARIO    NUMBER (10,2) NOT NULL,
    FNPRECIOTOTAL       NUMBER (10,2) NOT NULL,
    FIESTATUSSOL        NUMBER (5) NOT NULL,
    FIESTATUSCD         NUMBER (5) NOT NULL,
    FDFECHAACT          DATE NOT NULL,
    FIACTIVO            NUMBER(1) NOT NULL,
    FIRUTA              NUMBER(15) NOT NULL,
    FCMENSAJECD         VARCHAR2(100) NOT NULL,
    FIREINYECTA         NUMBER(1) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TASOLICITUDESDETALLE ON UNIFORMES.TASOLICITUDESDETALLE(FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE 
    ADD CONSTRAINT PK_TASOLICITUDESDETALLE
    PRIMARY KEY ( FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU ) 
    USING INDEX UNIFORMES.PK_TASOLICITUDESDETALLE;

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE
    ADD CONSTRAINT FK_TASOLICITUDESDETALLE_01 
    FOREIGN KEY ( FIFOLIOSOLICITUD )
    REFERENCES UNIFORMES.TASOLICITUDES ( FIFOLIOSOLICITUD );

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE
    ADD CONSTRAINT FK_TASOLICITUDESDETALLE_02 
	FOREIGN KEY ( FIIDTIPOPRENDA )
    REFERENCES UNIFORMES.TATIPOSPRENDA ( FIIDTIPOPRENDA );

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE
    ADD CONSTRAINT FK_TASOLICITUDESDETALLE_03 
	FOREIGN KEY ( FITALLA )
    REFERENCES UNIFORMES.TATIPOTALLA ( FITALLA );

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE
    ADD CONSTRAINT FK_TASOLICITUDESDETALLE_04
    FOREIGN KEY ( FIPAIS, FICANAL, FISUCURSAL )
    REFERENCES UNIFORMES.TATIENDAS ( FIPAIS, FICANAL, FISUCURSAL );

ALTER TABLE UNIFORMES.TASOLICITUDESDETALLE
    ADD CONSTRAINT FK_TASOLICITUDESDETALLE_05
    FOREIGN KEY ( FIESTATUSCD )
    REFERENCES UNIFORMES.TAESTATUSABASTO ( FIESTATUS );

--8) TABLA OPERATIVA REMISIONES X PEDIDO
CREATE TABLE UNIFORMES.TAREMISIONESXPEDIDO (
    FIFOLIOSOLICITUD NUMBER (20) NOT NULL,  --PK
    FIIDDETALLE      NUMBER (10) NOT NULL,  --PK
    FIPAIS           NUMBER (3) NOT NULL,   --PK
    FICANAL          NUMBER (10) NOT NULL,  --PK
    FISUCURSAL       NUMBER (10) NOT NULL,  --PK
    FIPEDIDO         NUMBER (10) NOT NULL,  --PK
    FISKU            NUMBER (20) NOT NULL,  --PK
    FIREMISION       NUMBER (20) NOT NULL,  --PK
    FICANTIDAD       NUMBER (3) NOT NULL,
    FIEMPLEADORECIBE NUMBER (10) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAREMISIONESXPEDIDO ON UNIFORMES.TAREMISIONESXPEDIDO(FIFOLIOSOLICITUD,FIIDDETALLE,FIPAIS,FICANAL,FISUCURSAL,FIPEDIDO,FISKU,FIREMISION)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;    

-- CREACION PK
ALTER TABLE UNIFORMES.TAREMISIONESXPEDIDO
    ADD CONSTRAINT PK_TAREMISIONESXPEDIDO 
    PRIMARY KEY ( FIFOLIOSOLICITUD,FIIDDETALLE,FIPAIS,FICANAL,FISUCURSAL,FIPEDIDO,FISKU,FIREMISION ) 
    USING INDEX UNIFORMES.PK_TAREMISIONESXPEDIDO;

-- CREACION FK
ALTER TABLE UNIFORMES.TAREMISIONESXPEDIDO
    ADD CONSTRAINT FK_TAREMISIONESXPEDIDO_01 
    FOREIGN KEY ( FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU )
    REFERENCES UNIFORMES.TASOLICITUDESDETALLE ( FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU );

--13) TABLA CATALOGO TIPO CALCULO PRECIO
CREATE TABLE UNIFORMES.TATIPOCALCULOPRECIO (
    FIIDTIPOCALCULO   NUMBER(3) NOT NULL,   --PK
    FCDESCRIPCION     VARCHAR2(50 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOCALCULOPRECIO ON UNIFORMES.TATIPOCALCULOPRECIO(FIIDTIPOCALCULO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOCALCULOPRECIO 
    ADD CONSTRAINT PK_TATIPOCALCULOPRECIO 
    PRIMARY KEY ( FIIDTIPOCALCULO ) 
    USING INDEX UNIFORMES.PK_TATIPOCALCULOPRECIO;

--28) TABLA CATALOGO TIPOS ERROR
CREATE TABLE UNIFORMES.TATIPOSERROR (
    FIIDERROR       NUMBER(5) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(100 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIPOSERROR ON UNIFORMES.TATIPOSERROR(FIIDERROR)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIPOSERROR 
    ADD CONSTRAINT PK_TATIPOSERROR 
    PRIMARY KEY ( FIIDERROR ) 
    USING INDEX UNIFORMES.PK_TATIPOSERROR;	

--15) TABLA OPERATIVA BITACORA SOLICITUD
CREATE TABLE UNIFORMES.TABITACORASOLICITUD (
    FIIDBITACORA     NUMBER (20) NOT NULL, --PK
    FIFOLIOSOLICITUD NUMBER (20) NOT NULL,
    FIIDDETALLE      NUMBER (10) NOT NULL,
    FIPEDIDO         NUMBER (10) NOT NULL,
    FCDATOSPROCESO   CLOB,
    FIESTATUSANT     NUMBER (5) NOT NULL,
    FIESTATUSNVO     NUMBER (5) NOT NULL,
    FDFECHA          DATE NOT NULL, --DEFAULT SYSDATE
    FCCOMENTARIOS    VARCHAR2 (1000 CHAR) DEFAULT ' ' NOT NULL,
    FIIDERROR        NUMBER (5) DEFAULT 0 NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TABITACORASOLICITUD ON UNIFORMES.TABITACORASOLICITUD(FIIDBITACORA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TABITACORASOLICITUD 
	ADD CONSTRAINT PK_TABITACORASOLICITUD 
	PRIMARY KEY ( FIIDBITACORA ) 
	USING INDEX UNIFORMES.PK_TABITACORASOLICITUD;

-- CREACION FK
ALTER TABLE UNIFORMES.TABITACORASOLICITUD
    ADD CONSTRAINT FK_TABITACORASOLICITUD_01 
	FOREIGN KEY ( FIESTATUSANT )
    REFERENCES UNIFORMES.TAESTATUSPEDIDOS ( FIIDESTATUSPEDIDO );

-- CREACION FK
ALTER TABLE UNIFORMES.TABITACORASOLICITUD
    ADD CONSTRAINT FK_TABITACORASOLICITUD_02 
	FOREIGN KEY ( FIESTATUSNVO )
    REFERENCES UNIFORMES.TAESTATUSPEDIDOS ( FIIDESTATUSPEDIDO );

-- CREACION FK
ALTER TABLE UNIFORMES.TABITACORASOLICITUD
    ADD CONSTRAINT FK_TABITACORASOLICITUD_03
	FOREIGN KEY ( FIIDERROR )
    REFERENCES UNIFORMES.TATIPOSERROR ( FIIDERROR );

--17) TABLA CATALOGO CANTIDADES
CREATE TABLE UNIFORMES.TACANTIDADES (
    FIIDTIPOSOLICITUD   NUMBER(3) NOT NULL,--PK
    FIIDTIPOPRENDA      NUMBER(3) NOT NULL,--PK
    FIMINIMO            NUMBER(1) NOT NULL,
    FIMAXIMO            NUMBER(3) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACANTIDADES ON UNIFORMES.TACANTIDADES(FIIDTIPOSOLICITUD, FIIDTIPOPRENDA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;    

-- CREACION PK
ALTER TABLE UNIFORMES.TACANTIDADES 
    ADD CONSTRAINT PK_TACANTIDADES 
    PRIMARY KEY ( FIIDTIPOSOLICITUD,FIIDTIPOPRENDA ) 
    USING INDEX UNIFORMES.PK_TACANTIDADES;

-- CREACION FK
ALTER TABLE UNIFORMES.TACANTIDADES
    ADD CONSTRAINT FK_TACANTIDADES_01 
    FOREIGN KEY ( FIIDTIPOSOLICITUD )
    REFERENCES UNIFORMES.TATIPOSOLICITUD ( FIIDTIPOSOLICITUD );

-- CREACION FK
ALTER TABLE UNIFORMES.TACANTIDADES
    ADD CONSTRAINT FK_TACANTIDADES_02
    FOREIGN KEY ( FIIDTIPOPRENDA )
    REFERENCES UNIFORMES.TATIPOSPRENDA ( FIIDTIPOPRENDA );

--18) TABLA CATALOGO PRECIOS
CREATE TABLE UNIFORMES.TAPRECIOS (
    FIIDTIPOSOLICITUD   NUMBER(3) NOT NULL,--PK
    FIIDTIPOPRENDA      NUMBER(3) NOT NULL,--PK
    FIIDTIPOCALCULO     NUMBER(3) NOT NULL,
    FNVALOR             NUMBER(10,2) NOT NULL
)	
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAPRECIOS ON UNIFORMES.TAPRECIOS(FIIDTIPOSOLICITUD, FIIDTIPOPRENDA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAPRECIOS 
    ADD CONSTRAINT PK_TAPRECIOS 
    PRIMARY KEY ( FIIDTIPOSOLICITUD,FIIDTIPOPRENDA ) 
    USING INDEX UNIFORMES.PK_TAPRECIOS;

-- CREACION FK
ALTER TABLE UNIFORMES.TAPRECIOS
    ADD CONSTRAINT FK_TAPRECIOS_01 
    FOREIGN KEY ( FIIDTIPOCALCULO )
    REFERENCES UNIFORMES.TATIPOCALCULOPRECIO ( FIIDTIPOCALCULO );

-- CREACION FK
ALTER TABLE UNIFORMES.TAPRECIOS
    ADD CONSTRAINT FK_TAPRECIOS_02
    FOREIGN KEY ( FIIDTIPOSOLICITUD )
    REFERENCES UNIFORMES.TATIPOSOLICITUD ( FIIDTIPOSOLICITUD );

-- CREACION FK
ALTER TABLE UNIFORMES.TAPRECIOS
    ADD CONSTRAINT FK_TAPRECIOS_03 
    FOREIGN KEY ( FIIDTIPOPRENDA )
    REFERENCES UNIFORMES.TATIPOSPRENDA ( FIIDTIPOPRENDA );

	
--20) TABLA OPERATIVA SOLICITUDES X CARGA
CREATE TABLE UNIFORMES.TASOLICITUDESXCARGA (
    FIFOLIOSOLICITUD   NUMBER(20) NOT NULL,--PK
    FIIDCARGA          NUMBER(10) NOT NULL --PK
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TASOLICITUDESXCARGA ON UNIFORMES.TASOLICITUDESXCARGA(FIFOLIOSOLICITUD, FIIDCARGA)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TASOLICITUDESXCARGA 
    ADD CONSTRAINT PK_TASOLICITUDESXCARGA 
    PRIMARY KEY ( FIFOLIOSOLICITUD,FIIDCARGA ) 
    USING INDEX UNIFORMES.PK_TASOLICITUDESXCARGA;

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESXCARGA
    ADD CONSTRAINT FK_TASOLICITUDESXCARGA_01 
    FOREIGN KEY ( FIIDCARGA )
    REFERENCES UNIFORMES.TACARGASSEMESTRALES ( FIIDCARGA );

-- CREACION FK
ALTER TABLE UNIFORMES.TASOLICITUDESXCARGA
    ADD CONSTRAINT FK_TASOLICITUDESXCARGA_02 
    FOREIGN KEY ( FIFOLIOSOLICITUD )
    REFERENCES UNIFORMES.TASOLICITUDES ( FIFOLIOSOLICITUD );
	
--25) TABLA MENUS
CREATE TABLE UNIFORMES.TAMENUS(
    FIIDMENU   	    	NUMBER(3) NOT NULL, --PK
    FCTITULO            VARCHAR2(300 CHAR) NOT NULL,
    FCDESCMENU   	VARCHAR2(300 CHAR) NOT NULL,
    FCRUTAENLACE      	VARCHAR2(300 CHAR) NOT NULL,
    FIAPLICACARGA     	NUMBER(1) NOT NULL,
    FIBLOQUEADOCARGA  	NUMBER(1) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAMENUS ON UNIFORMES.TAMENUS(FIIDMENU)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAMENUS 
	ADD (CONSTRAINT PK_TAMENUS PRIMARY KEY (FIIDMENU) USING INDEX UNIFORMES.PK_TAMENUS);

--26) TABLA TAMENUSFUNCIONESXNEGOCIO
CREATE TABLE UNIFORMES.TAMENUSFUNCIONESXNEGOCIO(
    FIIDMENU      NUMBER(3) NOT NULL,--PK
    FIIDNEGOCIO   NUMBER(3) NOT NULL,--PK
    FIFUNCIONSAP  NUMBER(10) NOT NULL--PK
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAMENUSFUNCIONESXNEGOCIO ON UNIFORMES.TAMENUSFUNCIONESXNEGOCIO(FIIDMENU, FIIDNEGOCIO, FIFUNCIONSAP)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAMENUSFUNCIONESXNEGOCIO 
    ADD (CONSTRAINT PK_TAMENUSFUNCIONESXNEGOCIO 
    PRIMARY KEY (FIIDMENU, FIIDNEGOCIO, FIFUNCIONSAP) 
    USING INDEX UNIFORMES.PK_TAMENUSFUNCIONESXNEGOCIO);

-- CREACION FK
ALTER TABLE UNIFORMES.TAMENUSFUNCIONESXNEGOCIO 
    ADD CONSTRAINT FK_TAMENUSFUNCIONESXNEGOCIO_01 
    FOREIGN KEY (FIIDMENU) 
    REFERENCES UNIFORMES.TAMENUS(FIIDMENU);

-- CREACION FK
ALTER TABLE UNIFORMES.TAMENUSFUNCIONESXNEGOCIO 
    ADD CONSTRAINT FK_TAMENUSFUNCIONESXNEGOCIO_02 
    FOREIGN KEY (FIIDNEGOCIO, FIFUNCIONSAP) 
    REFERENCES UNIFORMES.TAFUNCIONESXNEGOCIO(FIIDNEGOCIO,FIFUNCIONSAP);

-- 27) CREACION DE LA TABLA EQUIVALENCIACANALES CATALOGO
CREATE TABLE UNIFORMES.TAEQUIVALENCIACANALES(
    FICANALCECO     NUMBER(10) NOT NULL, --PK
    FICANAL         NUMBER(10) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(50 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAEQUIVALENCIACANALES ON UNIFORMES.TAEQUIVALENCIACANALES(FICANALCECO,FICANAL) 
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAEQUIVALENCIACANALES 	
    ADD CONSTRAINT PK_TAEQUIVALENCIACANALES 
    PRIMARY KEY (FICANALCECO,FICANAL) 
    USING INDEX UNIFORMES.PK_TAEQUIVALENCIACANALES;

CREATE TABLE UNIFORMES.TATIENDASDIRIP(
    FITIENDAID      NUMBER(10) NOT NULL, --PK
    FIPAISID        NUMBER(10) NOT NULL, --PK
    FICANAL         NUMBER(10) NOT NULL, --PK
    FICANALCECO     NUMBER(10) NOT NULL, --PK
    FCDESCRIPCION   VARCHAR2(100 CHAR) NOT NULL,	
    FCDIRECCIONIP   VARCHAR2(20 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TATIENDASDIRIP ON UNIFORMES.TATIENDASDIRIP(FITIENDAID,FIPAISID,FICANAL,FICANALCECO) 
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TATIENDASDIRIP 	
    ADD CONSTRAINT PK_TATIENDASDIRIP 
    PRIMARY KEY (FITIENDAID,FIPAISID,FICANAL,FICANALCECO) 
    USING INDEX UNIFORMES.PK_TATIENDASDIRIP;

-- CREACION FK
ALTER TABLE UNIFORMES.TATIENDASDIRIP 
    ADD CONSTRAINT FK_TATIENDASDIRIP_01 
    FOREIGN KEY (FICANAL,FICANALCECO) 
    REFERENCES UNIFORMES.TAEQUIVALENCIACANALES(FICANAL,FICANALCECO);

-- 29) CREACION DE LA TABLA CARGASXNEGOCIO
CREATE TABLE UNIFORMES.TACARGASXNEGOCIO(
    FIIDCARGA   NUMBER(5) NOT NULL, --PK
    FIIDNEGOCIO NUMBER(3) NOT NULL --PK
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACARGASXNEGOCIO ON UNIFORMES.TACARGASXNEGOCIO(FIIDCARGA,FIIDNEGOCIO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK 
ALTER TABLE UNIFORMES.TACARGASXNEGOCIO 
    ADD CONSTRAINT PK_TACARGASXNEGOCIO 
    PRIMARY KEY (FIIDCARGA,FIIDNEGOCIO) 
    USING INDEX UNIFORMES.PK_TACARGASXNEGOCIO;

-- CREACION FK
ALTER TABLE UNIFORMES.TACARGASXNEGOCIO 
    ADD CONSTRAINT FK_TACARGASXNEGOCIO_01 
    FOREIGN KEY (FIIDCARGA) 
    REFERENCES UNIFORMES.TACARGASSEMESTRALES(FIIDCARGA);
	
-- CREACION FK
ALTER TABLE UNIFORMES.TACARGASXNEGOCIO 
    ADD CONSTRAINT FK_TACARGASXNEGOCIO_02 
    FOREIGN KEY (FIIDNEGOCIO) 
    REFERENCES UNIFORMES.TANEGOCIOS(FIIDNEGOCIO);

-- 31) CREACION DE LA TABLA DIASSPPI
CREATE TABLE UNIFORMES.TADIASSPPI(
    FIANIO NUMBER(4) NOT NULL,
    FIMES  NUMBER(2) NOT NULL,
    FIDIA  NUMBER(2) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

--32) CREACION DE LA TABLA ESTATUSSPPI
CREATE TABLE UNIFORMES.TAESTATUSSPPI(
    FIESTATUS NUMBER(2) NOT NULL,   --PK
    FCESTATUS VARCHAR2(100 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAESTATUSSPPI ON UNIFORMES.TAESTATUSSPPI(FIESTATUS)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAESTATUSSPPI
    ADD CONSTRAINT PK_TAESTATUSSPPI
    PRIMARY KEY (FIESTATUS)
    USING INDEX UNIFORMES.PK_TAESTATUSSPPI;

CREATE TABLE UNIFORMES.TADISTRIBUCIONSPPI(
    FIFOLIOSOLICITUD    NUMBER(20) NOT NULL,--PK
    FIIDDETALLE         NUMBER(20) NOT NULL,--PK
    FIPEDIDO            NUMBER(10) NOT NULL,--PK
    FIPAIS              NUMBER(8) NOT NULL, --PK
    FICANAL             NUMBER(8) NOT NULL, --PK
    FISUCURSAL          NUMBER(8) NOT NULL, --PK
    FISKU		NUMBER(15) NOT NULL,--PK
    FIFOLIOCARGA        NUMBER(15) DEFAULT 0 NOT NULL,
    FIPORCAVANCE        NUMBER(3) DEFAULT 0 NOT NULL,
    FCDOCUMENTO         VARCHAR2(300 CHAR) DEFAULT ' ' NOT NULL,
    FCOBSERVACIONES     VARCHAR2(500 CHAR) DEFAULT ' ' NOT NULL,
    FDFECHA             DATE NOT NULL,
    FDFECHAACT          DATE NOT NULL,
    FIESTATUS           NUMBER(1) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TADISTRIBUCIONSPPI ON UNIFORMES.TADISTRIBUCIONSPPI(FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TADISTRIBUCIONSPPI
    ADD CONSTRAINT PK_TADISTRIBUCIONSPPI
    PRIMARY KEY (FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    USING INDEX UNIFORMES.PK_TADISTRIBUCIONSPPI;

-- CREACION FK
ALTER TABLE UNIFORMES.TADISTRIBUCIONSPPI
    ADD CONSTRAINT FK_TADISTRIBUCIONSPPI_01
    FOREIGN KEY (FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    REFERENCES UNIFORMES.TASOLICITUDESDETALLE (FIFOLIOSOLICITUD,FIIDDETALLE,FIPAIS,FICANAL,FISUCURSAL,FIPEDIDO,FISKU);

-- CREACION FK
ALTER TABLE UNIFORMES.TADISTRIBUCIONSPPI
    ADD CONSTRAINT FK_TADISTRIBUCIONSPPI_02
    FOREIGN KEY (FIESTATUS)
    REFERENCES UNIFORMES.TAESTATUSSPPI (FIESTATUS);

CREATE TABLE UNIFORMES.TANOTASCARGOENTRADA(
    FIFOLIOSOLICITUD    NUMBER(20) NOT NULL, --PK
    FIIDDETALLE         NUMBER(20) NOT NULL, --PK
    FIPEDIDO            NUMBER(10) NOT NULL, --PK
    FIPAIS              NUMBER(8) NOT NULL,  --PK
    FICANAL             NUMBER(8) NOT NULL,  --PK
    FISUCURSAL          NUMBER(8) NOT NULL,  --PK
    FISKU               NUMBER(15) NOT NULL, --PK
    FIFOLIOREMISION     NUMBER(15) DEFAULT -1 NOT NULL,             --WSABASTO
    FICANTIDADREQ       NUMBER(8) NOT NULL, 
    FICANTIDADSURT      NUMBER(8) DEFAULT -1 NOT NULL,              --WSABASTO
    FDFECHAREMISION     DATE,                                       --WSABASTO
    FIRUTA              NUMBER(15) DEFAULT -1 NOT NULL,             --WSABASTO
    FINOTACARGO         NUMBER(15) DEFAULT -1 NOT NULL,             --WSABASTO 
    FINOTAENTRADA       NUMBER(15) DEFAULT -1 NOT NULL,             --WSABASTO
    FCESTREMISION       VARCHAR2(1000 CHAR) DEFAULT ' ' NOT NULL,   --WSABASTO
    FCOBSERVACIONNC     VARCHAR2(1000 CHAR) DEFAULT ' ' NOT NULL,   --WSABASTO
    FCOBSERVACIONNE     VARCHAR2(1000 CHAR) DEFAULT ' ' NOT NULL,   --WSABASTO
    FDFECHAPROC         DATE NOT NULL,                      
    FDFECHAACT          DATE DEFAULT SYSDATE NOT NULL, 
    FCFECHAACTCD        VARCHAR2(100 CHAR) DEFAULT ' '      --WSABASTO 
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TANOTASCARGOENTRADA ON UNIFORMES.TANOTASCARGOENTRADA(FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TANOTASCARGOENTRADA
    ADD CONSTRAINT PK_TANOTASCARGOENTRADA
    PRIMARY KEY (FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU)
    USING INDEX UNIFORMES.PK_TANOTASCARGOENTRADA;

-- CREACION FK
ALTER TABLE UNIFORMES.TANOTASCARGOENTRADA
    ADD CONSTRAINT FK_TANOTASCARGOENTRADA_01
    FOREIGN KEY (FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU)
    REFERENCES UNIFORMES.TASOLICITUDESDETALLE(FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU);

CREATE TABLE UNIFORMES.TAESTATUSEMPLEADOADMIN(
    FIESTATUS       NUMBER (1) NOT NULL,    --PK
    FCDESCRIPCION   VARCHAR2(200 CHAR) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAESTATUSEMPLEADOADMIN ON UNIFORMES.TAESTATUSEMPLEADOADMIN(FIESTATUS)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAESTATUSEMPLEADOADMIN 
    ADD CONSTRAINT PK_TAESTATUSEMPLEADOADMIN
    PRIMARY KEY (FIESTATUS) 
    USING INDEX UNIFORMES.PK_TAESTATUSEMPLEADOADMIN;

CREATE TABLE UNIFORMES.TAEMPLEADOSADMINISTRADOR(
    FINUMEMPLEADO NUMBER (10) NOT NULL, --PK
    FCNOMBRE      VARCHAR2 (1000) NOT NULL,
    FCAREA        VARCHAR2 (1000) NOT NULL,
    FDULTIMOLOGIN DATE NOT NULL,
    FIESTATUS     NUMBER(1) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TAEMPLEADOSADMINISTRADOR ON UNIFORMES.TAEMPLEADOSADMINISTRADOR(FINUMEMPLEADO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TAEMPLEADOSADMINISTRADOR 
    ADD CONSTRAINT PK_TAEMPLEADOSADMINISTRADOR
    PRIMARY KEY (FINUMEMPLEADO)
    USING INDEX UNIFORMES.PK_TAEMPLEADOSADMINISTRADOR;

-- CREACION FK
ALTER TABLE UNIFORMES.TAEMPLEADOSADMINISTRADOR
    ADD CONSTRAINT FK_TAEMPLEADOSADMINISTRADOR_01
    FOREIGN KEY (FIESTATUS)
    REFERENCES UNIFORMES.TAESTATUSEMPLEADOADMIN(FIESTATUS);

CREATE TABLE UNIFORMES.TADESCUENTOSSAPXPEDIDO(
    FIFOLIOSOLICITUD    NUMBER(20) NOT NULL, --PK
    FIIDDETALLE         NUMBER(20) NOT NULL, --PK
    FIPEDIDO            NUMBER(10) NOT NULL, --PK
    FIPAIS              NUMBER(8) NOT NULL,  --PK
    FICANAL             NUMBER(8) NOT NULL,  --PK
    FISUCURSAL          NUMBER(8) NOT NULL,  --PK
    FISKU               NUMBER(15) NOT NULL, --PK
    FCSOCIEDAD          VARCHAR2(6 CHAR) NOT NULL,
    FDPAGO              DATE NOT NULL,
    FCREFERENCIA        VARCHAR2(60 CHAR) NOT NULL,
    FCCCNOMINA          VARCHAR2(6 CHAR) NOT NULL,
    FNTOTALDESCUENTO    NUMBER(6,2) NOT NULL,
    FISEMANADESCUENTO   NUMBER(2) NOT NULL,
    FNSALDO             NUMBER(5,2) NOT NULL,
    FNPAGO              NUMBER(5,2) NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TADESCUENTOSSAPXPEDIDO ON UNIFORMES.TADESCUENTOSSAPXPEDIDO(FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU,FISEMANADESCUENTO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TADESCUENTOSSAPXPEDIDO
    ADD CONSTRAINT PK_TADESCUENTOSSAPXPEDIDO
    PRIMARY KEY (FIFOLIOSOLICITUD,FIIDDETALLE,FIPEDIDO,FIPAIS,FICANAL,FISUCURSAL,FISKU,FISEMANADESCUENTO)
    USING INDEX UNIFORMES.PK_TADESCUENTOSSAPXPEDIDO;

-- CREACION FK
ALTER TABLE UNIFORMES.TADESCUENTOSSAPXPEDIDO
    ADD CONSTRAINT FK_TADESCUENTOSSAPXPEDIDO_01
    FOREIGN KEY (FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    REFERENCES UNIFORMES.TASOLICITUDESDETALLE(FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU);

CREATE TABLE UNIFORMES.TADISTRIBUCIONSAP(
    FIFOLIOSOLICITUD    NUMBER (20) NOT NULL, --PK
    FIIDDETALLE         NUMBER (10) NOT NULL, --PK
    FIPAIS              NUMBER (3) NOT NULL,  --PK
    FICANAL             NUMBER (10) NOT NULL, --PK	
    FISUCURSAL          NUMBER (10) NOT NULL, --PK	
    FIPEDIDO            NUMBER (10) NOT NULL, --PK
    FISKU               NUMBER (12) NOT NULL, --PK
    FICONSECUTIVO       NUMBER (10) NOT NULL, --PK
    FCREFERENCIA        VARCHAR2(20 CHAR) NOT NULL,
    FIESTATUS           NUMBER (3) NOT NULL,
    FCXMLREQUEST        CLOB NOT NULL,
    FCXMLRESPONSE       CLOB NOT NULL
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TADISTRIBUCIONSAP ON UNIFORMES.TADISTRIBUCIONSAP(FIFOLIOSOLICITUD,FIIDDETALLE,FIPAIS,FICANAL,FISUCURSAL,FIPEDIDO,FISKU,FICONSECUTIVO)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TADISTRIBUCIONSAP
    ADD CONSTRAINT PK_TADISTRIBUCIONSAP
    PRIMARY KEY (FIFOLIOSOLICITUD,FIIDDETALLE,FIPAIS,FICANAL,FISUCURSAL,FIPEDIDO,FISKU,FICONSECUTIVO)
    USING INDEX UNIFORMES.PK_TADISTRIBUCIONSAP;

-- CREACION FK
ALTER TABLE UNIFORMES.TADISTRIBUCIONSAP
    ADD CONSTRAINT FK_TADISTRIBUCIONSAP_01
    FOREIGN KEY (FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU)
    REFERENCES  UNIFORMES.TASOLICITUDESDETALLE(FIFOLIOSOLICITUD, FIIDDETALLE, FIPAIS, FICANAL, FISUCURSAL, FIPEDIDO, FISKU);

-- ESTRUCTURAS CREADAS **********************************************************************************

--TYPE ARRAYS - COLLECTIONS
CREATE OR REPLACE TYPE UNIFORMES.TYPTIENDADIRIP AS OBJECT (
    FITIENDAID    NUMBER(10),         
    FIPAISID      NUMBER(10),        
    FICANAL       NUMBER(10),         
    FICANALCECO   NUMBER(10),         
    FCDESCRIPCION VARCHAR2(100 CHAR), 
    FCDIRECCIONIP VARCHAR2(20 CHAR)  
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPARRTIENDASDIRIP AS TABLE OF UNIFORMES.TYPTIENDADIRIP;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPECONFIRMACIONENTREGA AS OBJECT ( 
    FIFOLIOSOLICITUD    NUMBER(20),
    FIIDDETALLE         NUMBER(10),
    FIPAIS              NUMBER(3),
    FICANAL             NUMBER(10),
    FIIDSUCURSAL        NUMBER(10),
    FINUMPEDIDO         NUMBER(10),
    FISKU               NUMBER(20),
    FIIDTIPOEVENTO      NUMBER(5),
    FCDATOS             CLOB,
    FIIDESTATUSANT      NUMBER(3),
    FIIDESTATUSNVO      NUMBER(3),
    FIERROR             NUMBER(5),
    FCCOMENTARIOS       VARCHAR2(100)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRCONFIRMACIONENTREGA AS TABLE OF UNIFORMES.TYPECONFIRMACIONENTREGA;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPEDESCUENTOSSAP AS OBJECT ( 
    FIFOLIOSOLICITUD	NUMBER(10),
    FIPEDIDO		NUMBER(10),
    FCSOCIEDAD     	VARCHAR2(4 CHAR),
    FCREFERENCIA        VARCHAR2(20 CHAR),
    FCCNOMINA      	VARCHAR2(4 CHAR),
    FNTOTAL        	NUMBER(13,2),
    FDFECHAPAGO     	DATE,
    FISEMACTUAL    	NUMBER(2),
    FNSALDO      	NUMBER(15,2),
    FNPAGO         	NUMBER(15,2)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRDESCUENTOSSAP AS TABLE OF UNIFORMES.TYPEDESCUENTOSSAP;
/
CREATE OR REPLACE TYPE UNIFORMES.TYPENOTACARGOENTRADA AS OBJECT 
( 
    FIFOLIOSOLICITUD    NUMBER(20),
    FIIDDETALLE         NUMBER(20),
    FIPAIS              NUMBER(8),
    FICANAL             NUMBER(8),
    FIPEDIDO			NUMBER(10),
    FISUCURSAL			NUMBER(8),
    FISKU				NUMBER(15),
    FICANTIDADREQ       NUMBER(8),
    FICANTIDADSURT      NUMBER(8),
    FIFOLIOREMISION		NUMBER(15),
    FDFECHAREMISION		DATE,
    FIRUTA				NUMBER(15),
    FINOTACARGO			NUMBER(15),
    FINOTAENTRADA		NUMBER(15),
    FCESTREMISION		VARCHAR(1000 CHAR),
    FCOBSERVACIONNC		VARCHAR(1000 CHAR),
    FCOBSERVACIONNE		VARCHAR(1000 CHAR),
    FCFECHAACTCD		VARCHAR(100 CHAR),
    FIERROR             NUMBER(1),
    FCMSJERROR          VARCHAR(500 CHAR),
    FCXMLRESPONSE       CLOB,
    FIESTATUSSOL        NUMBER (5)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRNOTACARGOENTRADA AS TABLE OF UNIFORMES.TYPENOTACARGOENTRADA;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPEPRENDA AS OBJECT(
    FIPAIS              NUMBER(3),
    FICANAL             VARCHAR2(40 CHAR),
    FISUCURSAL          NUMBER(10),
    FIIDTIPOPRENDA      NUMBER(3),
    FITALLA             NUMBER(5),
    FICANTIDAD          NUMBER(10),
    FIPRECIOUNITARIO    NUMBER(10,2)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRPRENDAS AS TABLE OF UNIFORMES.TYPEPRENDA;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPESOLICITUDDETALLE AS OBJECT(
    FIFOLIOSOLICITUD    NUMBER (20), 	--PK*
    FIIDDETALLE         NUMBER (10), 	--PK*
    FIPAIS              NUMBER (3),  	--PK*
    FICANAL             NUMBER (10), 	--PK*
    FISUCURSAL          NUMBER (10), 	--PK*	
    FIPEDIDO            NUMBER (10), 	--PK*
    FISKU               NUMBER (12), 	--PK*
    FIRUTA              NUMBER (10), 
    FIESTATUSCD         NUMBER (10),
    FIESTATUSSOL        NUMBER (5),
    FCXMLRESPONSE       CLOB,
    FCDESCRIPCIONBIT    VARCHAR2 (100 CHAR),
    FCMENSAJECD         VARCHAR2 (100 CHAR),
    FIESTATUSREMISION   NUMBER(5),
    FIERROR             NUMBER(1),
    FCMSJERROR          VARCHAR2 (500 CHAR)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRSOLICITUDDETALLE AS TABLE OF UNIFORMES.TYPESOLICITUDDETALLE;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPESOLICITUDPRENDA AS OBJECT(
    FIEMPLEADO NUMBER(10),
    FIIDTIPOSOLICITUD NUMBER(3),
    FIIDNEGOCIO NUMBER(3),
    FIFUNCIONSAP NUMBER(10),
    FIEMPLEADOCAPTURA NUMBER(10),
    PRENDAS UNIFORMES.TYPEARRPRENDAS
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRSOLICITUDPRENDA AS TABLE OF UNIFORMES.TYPESOLICITUDPRENDA;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPEDISTRIBUCIONSAP AS OBJECT ( 
    FIFOLIOSOLICITUD    NUMBER(20),    
    FIIDDETALLE         NUMBER (10),
    FIPAIS              NUMBER(3),
    FICANAL             NUMBER(10),
    FIIDSUCURSAL        NUMBER(10),
    FIPEDIDO            NUMBER(10),
    FISKU               NUMBER(20),
    FCREFERENCIASAP     VARCHAR2(20 CHAR),
    FIESTATUSSAP        NUMBER(3),
    FCXMLREQUEST        CLOB,
    FCXMLRESPONSE       CLOB,
    FCTEXTXMLRESPONSE	VARCHAR2(500 CHAR),
    FIIDERROR           NUMBER(5)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRDISTRIBUCIONSAP AS TABLE OF UNIFORMES.TYPEDISTRIBUCIONSAP;
/
CREATE OR REPLACE TYPE UNIFORMES.TYPECARGASPPI AS OBJECT(
    FIFOLIOSOLICITUD    NUMBER(20),
    FIIDDETALLE         NUMBER(20),
    FIPEDIDO            NUMBER(10),
    FCDATOSPROC         CLOB,
    FIESTATUSPEDIDO     NUMBER(3),
    FIPAIS              NUMBER(8),
    FICANAL             NUMBER(8),
    FISUCURSAL          NUMBER(8),
    FISKU		NUMBER(15),
    FIFOLIOCARGA        NUMBER(15),
    FIPORCAVANCE        NUMBER(3),
    FCDOCUMENTO         VARCHAR2(300 CHAR),
    FCOBSERVACIONES     VARCHAR2(500 CHAR),
    FIESTATUS           NUMBER(1)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPEARRCARGASPPI AS TABLE OF UNIFORMES.TYPECARGASPPI;
/

CREATE OR REPLACE TYPE UNIFORMES.TIPO_CARGAS IS TABLE OF NUMBER(10);
/

CREATE OR REPLACE TYPE UNIFORMES.TYPNEGOCIO AS OBJECT(
    FINEGOCIO NUMBER(3),
    FCNEGOCIO VARCHAR2(100 CHAR)
);
/
CREATE OR REPLACE TYPE UNIFORMES.TYPARRNEGOCIO AS TABLE OF UNIFORMES.TYPNEGOCIO;
/

CREATE OR REPLACE TYPE UNIFORMES.TYPCARGA AS OBJECT(
    FIIDCARGA       NUMBER(5),
    FCDESCRIPCION   VARCHAR2(160 CHAR),
    FDFECHAINICIAL  VARCHAR2(15 CHAR),
    FDFECHAFINAL    VARCHAR2(15 CHAR),
    FIESTATUS       NUMBER(1),
    FIGENERARPEDIDO NUMBER(1),
    NEGOCIOS        UNIFORMES.TYPARRNEGOCIO
);
/
--- INDICES
CREATE INDEX UNIFORMES.IX_TASOLICITUDESDETALLE_01 ON UNIFORMES.TASOLICITUDESDETALLE
(FIFOLIOSOLICITUD)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;

CREATE INDEX UNIFORMES.IX_TASOLICITUDES_01 ON UNIFORMES.TASOLICITUDES
(FIIDEMPLEADO)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;

CREATE INDEX UNIFORMES.IX_TAFUNCIONESXNEGOCIO_01 ON UNIFORMES.TAFUNCIONESXNEGOCIO
(FIFUNCIONSAP, FICANAL)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;

CREATE INDEX UNIFORMES.IX_TATIENDAS_01 ON UNIFORMES.TATIENDAS
(FISUCURSAL)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;

CREATE INDEX UNIFORMES.IX_TANOTASCARGOENTRADA_01 ON UNIFORMES.TANOTASCARGOENTRADA
(FIPEDIDO, FISUCURSAL, FISKU)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;

CREATE INDEX UNIFORMES.IX_TADISTRIBUCIONSPPI_01 ON UNIFORMES.TADISTRIBUCIONSPPI
(FICANAL)
TABLESPACE TBS_UNIFORMES_OPE_IDX
LOGGING;