-- TABLA CATALOGO CD
CREATE TABLE UNIFORMES.TACENTROSDISTRIBUCION (
	FIPAIS			NUMBER(3) NOT NULL, 	--PK
	FICD   			NUMBER(10) NOT NULL,	--PK
	FCDESCRIPCION	VARCHAR2(100) NOT NULL,
	FIIDMANHATAN	NUMBER(10) NOT NULL,
	FIACTIVO		NUMBER(1) NOT NULL
)    
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;
	
-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACENTROSDISTRIBUCION ON UNIFORMES.TACENTROSDISTRIBUCION(FIPAIS,FICD)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TACENTROSDISTRIBUCION 
    ADD CONSTRAINT PK_TACENTROSDISTRIBUCION 
    PRIMARY KEY (FIPAIS,FICD) 
    USING INDEX UNIFORMES.PK_TACENTROSDISTRIBUCION;
	
-- TABLA CATALOGO CDXTIENDAS
CREATE TABLE UNIFORMES.TACDXTIENDAS (
	FIPAIS			NUMBER(3) NOT NULL, 	--PK
	FICD   			NUMBER(10) NOT NULL,	--PK
	FICANAL			NUMBER(10) NOT NULL,	--PK		
    FISUCURSAL  	NUMBER(10) NOT NULL, 	--PK
	FIIDNEGOCIO		NUMBER(3) NOT NULL,		--PK
	FIACTIVO		NUMBER(1) NOT NULL
)    
    TABLESPACE TBS_UNIFORMES_CAT_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACDXTIENDAS ON UNIFORMES.TACDXTIENDAS(FIPAIS,FICANAL,FISUCURSAL,FIIDNEGOCIO,FICD)
    LOGGING
    TABLESPACE TBS_UNIFORMES_CAT_IDX;

-- CREACION PK
ALTER TABLE UNIFORMES.TACDXTIENDAS 
    ADD CONSTRAINT PK_TACDXTIENDAS 
    PRIMARY KEY (FIPAIS,FICANAL,FISUCURSAL,FIIDNEGOCIO,FICD ) 
    USING INDEX UNIFORMES.PK_TACDXTIENDAS;
	
-- CREACION FK
ALTER TABLE UNIFORMES.TACDXTIENDAS 
    ADD CONSTRAINT FK_TACDXTIENDAS_01 
    FOREIGN KEY ( FIPAIS,FICANAL,FISUCURSAL ) 
    REFERENCES UNIFORMES.TATIENDAS ( FIPAIS,FICANAL,FISUCURSAL );
	
-- CREACION FK
ALTER TABLE UNIFORMES.TACDXTIENDAS 
    ADD CONSTRAINT FK_TACDXTIENDAS_02 
    FOREIGN KEY ( FIIDNEGOCIO ) 
    REFERENCES UNIFORMES.TANEGOCIOS ( FIIDNEGOCIO );
	
-- CREACION FK
ALTER TABLE UNIFORMES.TACDXTIENDAS 
    ADD CONSTRAINT FK_TACDXTIENDAS_03
    FOREIGN KEY ( FIPAIS,FICD ) 
    REFERENCES UNIFORMES.TACENTROSDISTRIBUCION ( FIPAIS,FICD );

-- TABLA NOTASCARGOENTRADA
ALTER TABLE UNIFORMES.TANOTASCARGOENTRADA
	ADD (FCFOLIOWM VARCHAR2(100 CHAR) NOT NULL);

-- MODIFICACION TYPE
ALTER TYPE UNIFORMES.TYPENOTACARGOENTRADA ADD ATTRIBUTE (FCFOLIOWM VARCHAR(100 CHAR))
CASCADE;

-- TABLA CARGASXCD
CREATE TABLE UNIFORMES.TACARGASXCD(
    FIIDCARGA 	NUMBER(5) NOT NULL,		--PK
	FICD		NUMBER(10) NOT NULL,	--PK	 	
	FIPAIS		NUMBER(3) NOT NULL		--PK
)
    TABLESPACE TBS_UNIFORMES_OPE_DAT
    LOGGING;

-- CREACION INDICE
CREATE UNIQUE INDEX UNIFORMES.PK_TACARGASXCD ON UNIFORMES.TACARGASXCD(FIIDCARGA,FICD,FIPAIS)
    LOGGING
    TABLESPACE TBS_UNIFORMES_OPE_IDX;

-- CREACION PK 
ALTER TABLE UNIFORMES.TACARGASXCD
    ADD CONSTRAINT PK_TACARGASXCD 
    PRIMARY KEY (FIIDCARGA,FICD,FIPAIS) 
    USING INDEX UNIFORMES.PK_TACARGASXCD;

-- CREACION FK
ALTER TABLE UNIFORMES.TACARGASXCD 
    ADD CONSTRAINT FK_TACARGASXCD_01 
    FOREIGN KEY (FIIDCARGA) 
    REFERENCES UNIFORMES.TACARGASSEMESTRALES(FIIDCARGA);
	
-- CREACION FK
ALTER TABLE UNIFORMES.TACARGASXCD 
    ADD CONSTRAINT FK_TACARGASXCD_02 
    FOREIGN KEY (FIPAIS,FICD) 
    REFERENCES UNIFORMES.TACENTROSDISTRIBUCION(FIPAIS,FICD);
    
	
	
CREATE TYPE NUMBER_ARRAY AS TABLE OF NUMBER;
/
	

